# Generated by Django 4.1.7 on 2023-05-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_topic_event_host_message_event_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
